version: '3'
services:
  frontend:
    image: frontend_image 
    container_name: frontend_container
    ports: 
      - "3000:3000"
    volumes:
      - "xyzuploads:/uploads"
    networks:   
      - "xyznetwork"
    depends_on:
      -  backend
  backend:
    image: backend_image 
    container_name: backend_container
    ports: 
      - "5000:5000"
    volumes:
      - "xyzuploads:/uploads"
    networks:   
      - "xyznetwork"
    depends_on:
      -  mongo
  mongo:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:   
      - "xyznetwork"
networks:
    xyznetwork:
volumes:  
    xyzuploads:
    mongodb-data:  
    

    



